./FastTree LASV_L_alignment_2_MRU.fasta > LASV_L_alignment_2_MRU.tree
./FastTree LASV_S_alignment_2_MRU.fasta > LASV_S_alignment_2_MRU.tree
./FastTree LASV_L_alignment_2_NGA.fasta > LASV_L_alignment_2_NGA.tree
./FastTree LASV_S_alignment_2_NGA.fasta > LASV_S_alignment_2_NGA.tree
./FastTree LASV_L_alignment_3_MRU.fasta > LASV_L_alignment_3_MRU.tree
./FastTree LASV_S_alignment_3_MRU.fasta > LASV_S_alignment_3_MRU.tree
./FastTree LASV_L_alignment_3_NI1.fasta > LASV_L_alignment_3_NI1.tree
./FastTree LASV_S_alignment_3_NI1.fasta > LASV_S_alignment_3_NI1.tree
./FastTree LASV_L_alignment_3_NI2.fasta > LASV_L_alignment_3_NI2.tree
./FastTree LASV_S_alignment_3_NI2.fasta > LASV_S_alignment_3_NI2.tree
./FastTree LASV_L_alignment_3_NI3.fasta > LASV_L_alignment_3_NI3.tree
./FastTree LASV_S_alignment_3_NI3.fasta > LASV_S_alignment_3_NI3.tree
